### ISSUE TITLE
Lazy loading components creates undesirable side effects

### ISSUE THREAD

**Issue by Mochibunn** [Mochibunn/product-lazypress#40]
Inside of `App.jsx`, lines **16** and **17** introduce a lazy loading mechanic for the sign in and sign up components.
This lazy loading behavior might have an unfortunate side effect that makes it very confusing to tell if the page is loaded or not for when you have a slower than desired internet connection speed *(guess how I found out about that ;p )*

Perhaps, it would be better to not have them lazy load as they are important components in that scenario *!*

![image](https://github.com/Mochibunn/product-lazypress/assets/103283434/d863017f-fb4c-4af9-b10b-ca15086a4fa9)

**Comment by priyankapasrija** [comment]
I removed it from sign in and sign up components...Thanks for addressing
